language: java
# Building a Java project
#   https://docs.travis-ci.com/user/languages/java
#
# how to install and set jdk on travis:
# - Testing Against Multiple JDKs
#   https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
# - JVM images
#   https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
# - Customizing the Build / Build Matrix
#   https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix


# The Ubuntu Linux Build Environments
#   https://docs.travis-ci.com/user/reference/linux/
# The macOS Build Environment
#   https://docs.travis-ci.com/user/reference/osx/
# Installing Dependencies
#   https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos

# Job Lifecycle
#   https://docs.travis-ci.com/user/job-lifecycle/

os: linux
dist: trusty

addons:
  apt:
    packages:
      - openjdk-6-jdk
  homebrew:
    packages:
    - coreutils
    - gnu-sed
    - java6

jobs:
  include:
    - name: ttl core lib test under linux
      script:
        - scripts/integration-test.sh
      after_success:
        - ./scripts/codecov.sh
    - name: ttl core lib test under osx
      os: osx
      osx_image: xcode11.3
      install:
        - export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:$PATH
      script:
        - scripts/integration-test.sh
      after_success:
        - ./scripts/codecov.sh
    - name: ttl extension libs test under linux
      script:
        - ttl-integrations/sample-ttl-agent-extension-transformlet/scripts/integration-test.sh

branches:
  except:
    - appveyor

after_script:
  - git status --ignored

before_cache:
  # clear TTL maven self install
  - rm -rf $HOME/.m2/repository/com/alibaba/transmittable-thread-local
# Caching Dependencies and Directories
# https://docs.travis-ci.com/user/caching/
cache:
  - pip
  - directories:
    - $HOME/.m2
    - $HOME/.sdkman
    - $HOME/.cache/pip
